pipeline{
    agent any
      
    parameters{
        string(name: "SPEC", defaultValue: "/Test/cypress-e2e-framework/cypress/**/**", description: "Ejecuta todos los casos de prueba")
        choice(name: "BROWSER", choices: ['chrome', 'edge', 'firefox'], description: "Eliga un browser para las pruebas")
    }
    options{
        ansiColor('xterm')  
    } 
    
    stages{
        // stage('Checkout') {
        //     steps {
        //         git branch: 'main', url: 'https://github.com/txmcode/txm-devOps.git'
        //     }
        // }
        stage('Testing'){
            steps{
                bat "npm i"
                bat "npx cypress run --browser ${BROWSER} --spec ${SPEC}"
            }
        }
    }

    post{
        always{
            publishHTML(allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'cypress/report', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])
        }
    }
}

// pipeline{
//     agent any
      
//     parameters{
//         string(name: "SPEC", defaultValue: "/Test/cypress-e2e-framework/cypress/**/**", description: "Ejecuta todos los casos de prueba")
//         choice(name: "BROWSER", choices: ['chrome', 'edge', 'firefox']), description: "Eliga un browser para las pruebas"
//     }
//     options{
//         ansiColor('xterm')  
//     } 
    
//     stages{
//         stage('Testing'){
//             steps{
//                 bat "npm i"
//                 bat "npx cypress run --browser ${BROWSER} --spec ${SPEC}"
//             }
//         }
//     }

//     post{
//         always{
//             publishHTML(allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'cypress/report', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])
//         }
//     }
// }
